@startuml assignment_5
skinparam linetype ortho
hide empty methods
hide empty fields
hide circle

title Assigment 5, Read Number, Testing if it's Prime and Printing the Result

start
partition "Read Number" {
    :Write to the console: "Input a 2 digit decimal number: ";
    :Read first digit;
    :Multiply first digit by 10;
    :Read second digit;
    :Add second digit to first digit;
}

partition "Testing if it's Prime" {
    :Get a number to test if it's prime;
    if (Number is even) then (yes)
        :Number is not prime;
    else (no)
        :Check if number is 1 or less;
        if (Number is 1 or less) then (yes)
            :Number is not prime;
        else (no)
            :Set Divisor to 3;
            :Check if divisor is bigger than half the number;
            while (divisor is not bigger than half the number) is (yes)
                :Check if number is divisible by divisor;
                if (Number is divisible by divisor) then (yes)
                    :Number is prime;
                else (no)
                    :Increase divisor by 2;
                endif
            endwhile (no)
            :Number is not prime;
        endif
    endif
}

partition "Printing the Result" {
    if (Register 0 is 0) then (true)
        :Print to the console "The number is not prime";
    else (false)
        :Print to the console "The number is prime";
    endif
}
end

@enduml