@startuml assignment_2
skinparam linetype ortho
hide empty methods
hide empty fields
hide circle

title Assigment 2, Reading Numbers from the Console

start
:Write to the console: "Input a 2 digit decimal number: ";
:Read first input character;
while (First input character is not a digit) is (true)
    :Write to the console: "Input must be a digit between 0-9";
endwhile (false)
:Multiply first digit by 10;
:Read second input character;
while (Second input character is not a digit) is (true)
    :Write to the console: "Input must be a digit between 0-9";
endwhile (false)
:Add second digit to first digit;
end

@enduml