@startuml assignment_3
skinparam linetype ortho
hide empty methods
hide empty fields
hide circle

title Assigment 3, Testing if a Number is Prime

start
:Get a number to test if it's prime;
if (Number is even) then (yes)
    :Number is not prime;
else (no)
    :Check if number is 1 or less;
    if (Number is 1 or less) then (yes)
        :Number is not prime;
    else (no)
        :Set Divisor to 3;
        :Check if divisor is bigger than half the number;
        while (divisor is not bigger than half the number) is (yes)
            :Check if number is divisible by divisor;
            if (Number is divisible by divisor) then (yes)
                :Number is prime;
            else (no)
                :Increase divisor by 2;
            endif
        endwhile (no)
        :Number is not prime;
    endif
endif
end

@enduml